import * as PDFJS from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
PDFJS.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const PDFLIB=await import('https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/+esm');
const $=s=>document.querySelector(s),canvas=$('#canvas'),sheet=$('#sheet'),layer=$('#layer'),textLayer=$('#textLayer');
const BASE_SCALE=1.45,MAX_BYTES=100*1024*1024;
let sourceBytes=null,pdf=null,pages=[],current=0,zoom=1,tool='select',selectedId='',history=[],future=[],baseName='documento',renderSerial=0,editSnapshotId='';
const deep=v=>JSON.parse(JSON.stringify(v));
function toast(message){const e=$('#toast');e.textContent=message;e.classList.remove('hide');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.add('hide'),3500)}
function snapshot(){history.push(JSON.stringify(pages));if(history.length>50)history.shift();future=[];updateButtons()}
function restore(from,to){if(!from.length)return;to.push(JSON.stringify(pages));pages=JSON.parse(from.pop());selectedId='';editSnapshotId='';render();updateButtons()}
function updateButtons(){const loaded=!!pdf;$('#download').disabled=!loaded;$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;$('#remove').disabled=!selectedId;$('#prev').disabled=!loaded||current<=0;$('#next').disabled=!loaded||current>=pages.length-1;$('#deletepage').disabled=!loaded||pages.length<=1}
function setTool(next){tool=next;$('#tools').querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('on',b.dataset.tool===tool));if(tool==='image'){$('#imginput').click();tool='select';setTool('select')}}
function pageSpec(){return pages[current]}
function pct(n,total){return total?100*n/total:0}
function px(n,total){return total*n/100}
function clamp(v,min,max){return Math.max(min,Math.min(max,v))}
function hex(r,g,b){return '#'+[r,g,b].map(v=>Math.round(clamp(v,0,255)).toString(16).padStart(2,'0')).join('')}
function sampleColors(x,y,w,h){try{const ctx=canvas.getContext('2d',{willReadFrequently:true});const W=canvas.width,H=canvas.height;const left=Math.max(0,Math.floor(x)),top=Math.max(0,Math.floor(y)),right=Math.min(W,Math.ceil(x+w)),bottom=Math.min(H,Math.ceil(y+h));if(right-left<2||bottom-top<2)return{bg:'#ffffff',fg:'#111111'};const border=[],inside=[];const step=Math.max(1,Math.floor(Math.min(right-left,bottom-top)/12));for(let yy=top;yy<bottom;yy+=step){for(let xx=left;xx<right;xx+=step){const d=ctx.getImageData(xx,yy,1,1).data,lum=.2126*d[0]+.7152*d[1]+.0722*d[2];inside.push([d[0],d[1],d[2],lum]);if(xx-left<step*2||right-xx<step*2||yy-top<step*2||bottom-yy<step*2)border.push([d[0],d[1],d[2],lum])}}const light=(border.length?border:inside).sort((a,b)=>b[3]-a[3]).slice(0,Math.max(1,Math.floor((border.length||inside.length)*.55)));const dark=inside.sort((a,b)=>a[3]-b[3]).slice(0,Math.max(1,Math.floor(inside.length*.25)));const avg=a=>a.reduce((s,p)=>[s[0]+p[0],s[1]+p[1],s[2]+p[2]],[0,0,0]).map(v=>v/a.length);const b=avg(light),f=avg(dark);return{bg:hex(...b),fg:hex(...f)}}catch{return{bg:'#ffffff',fg:'#111111'}}}
async function loadFile(file){if(!file)return;if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf')return toast('Scegli un file PDF.');if(file.size>MAX_BYTES)return toast('Il PDF supera il limite di 100 MB.');try{sourceBytes=await file.arrayBuffer();pdf=await PDFJS.getDocument({data:sourceBytes.slice(0)}).promise;pages=Array.from({length:pdf.numPages},(_,i)=>({source:i,rot:0,items:[]}));current=0;zoom=1;baseName=file.name.replace(/\.pdf$/i,'')||'documento';$('#filename').textContent=file.name;$('#welcome').classList.add('hide');sheet.classList.remove('hide');$('#bar').classList.remove('hide');history=[];future=[];selectedId='';setTool('select');await render();updateButtons()}catch(e){console.error(e);toast('PDF protetto, danneggiato o non leggibile. Rimuovi la password e riprova.')}}
function textStyleName(family=''){const f=family.toLowerCase();return f.includes('times')?'times':f.includes('courier')||f.includes('mono')?'courier':'helvetica'}
async function render(){if(!pdf)return;const serial=++renderSerial;current=clamp(current,0,pages.length-1);const spec=pageSpec(),page=await pdf.getPage(spec.source+1),rotation=(page.rotate+spec.rot)%360,viewport=page.getViewport({scale:BASE_SCALE*zoom,rotation});if(serial!==renderSerial)return;canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';sheet.style.width=viewport.width+'px';sheet.style.height=viewport.height+'px';layer.style.width=textLayer.style.width=viewport.width+'px';layer.style.height=textLayer.style.height=viewport.height+'px';const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport}).promise;if(serial!==renderSerial)return;renderItems(viewport);await renderTextHits(page,viewport,spec);$('#pageinfo').textContent=(current+1)+' / '+pages.length;$('#zoominfo').textContent=Math.round(zoom*100)+'%';updateButtons()}
async function renderTextHits(page,viewport,spec){textLayer.innerHTML='';let content;try{content=await page.getTextContent()}catch{content={items:[],styles:{}}}const replaced=new Set(spec.items.filter(i=>i.kind==='replace').map(i=>i.originalId));let count=0;content.items.forEach((it,index)=>{if(!('str'in it)||!it.str||!it.str.trim())return;const originalId=`${spec.source}:${index}`;if(replaced.has(originalId))return;const tx=PDFJS.Util.transform(viewport.transform,it.transform),fontH=Math.max(6,Math.hypot(tx[2],tx[3])),angle=Math.atan2(tx[1],tx[0]),x=tx[4],y=tx[5]-fontH,w=Math.max(4,(it.width||it.str.length*fontH*.48)*viewport.scale),h=Math.max(fontH,8);if(x>viewport.width||y>viewport.height||x+w<0||y+h<0)return;const span=document.createElement('span');span.className='text-hit';span.textContent=it.str;span.title='Clicca per modificare: '+it.str;span.style.left=x+'px';span.style.top=y+'px';span.style.width=w+'px';span.style.height=h+'px';span.style.fontSize=fontH+'px';span.style.transform=angle?`rotate(${angle}rad)`:'';span.onclick=e=>{e.stopPropagation();if(tool!=='select')return;const colors=sampleColors(x,y,w,h),style=content.styles?.[it.fontName]||{};editOriginal({originalId,text:it.str,x:pct(x,viewport.width),y:pct(y,viewport.height),w:pct(w,viewport.width),h:pct(h,viewport.height),fontSize:fontH/(BASE_SCALE*zoom),fontFamily:style.fontFamily||'Helvetica',fontKey:textStyleName(style.fontFamily),color:colors.fg,background:colors.bg})};textLayer.appendChild(span);count++});const note=$('#scanNote');if(count===0&&!spec.items.some(i=>i.kind==='replace')){note.textContent='Questo PDF non contiene testo selezionabile: probabilmente è una scansione. Puoi comunque usare “Copri area” e “Aggiungi testo”.';note.classList.remove('hide');clearTimeout(note.timer);note.timer=setTimeout(()=>note.classList.add('hide'),6500)}else note.classList.add('hide')}
function renderItems(viewport){layer.innerHTML='';pageSpec().items.forEach(item=>{const el=document.createElement('div');el.className='item '+item.kind+(item.id===selectedId?' selected':'');el.dataset.id=item.id;el.style.left=px(item.x,viewport.width)+'px';el.style.top=px(item.y,viewport.height)+'px';el.style.width=px(item.w,viewport.width)+'px';el.style.height=Math.max(3,px(item.h,viewport.height))+'px';if(item.kind==='text'||item.kind==='replace'){el.contentEditable='true';el.spellcheck=false;el.textContent=item.text;el.style.fontSize=Math.max(6,item.fontSize*BASE_SCALE*zoom)+'px';el.style.fontFamily=item.fontKey==='times'?"'Times New Roman',serif":item.fontKey==='courier'?"'Courier New',monospace":"Arial,Helvetica,sans-serif";el.style.color=item.color||'#111';if(item.kind==='replace')el.style.background=item.background||'#fff';el.onfocus=()=>{selectedId=item.id;if(editSnapshotId!==item.id){snapshot();editSnapshotId=item.id}updateButtons();el.classList.add('selected')};el.oninput=()=>{item.text=el.textContent||'';const r=el.getBoundingClientRect(),pr=layer.getBoundingClientRect();item.w=Math.max(item.w,pct(r.width,pr.width));item.h=Math.max(item.h,pct(r.height,pr.height))};el.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();el.blur()}};el.onblur=()=>{editSnapshotId='';render()};el.onclick=e=>{e.stopPropagation();selectedId=item.id;updateButtons()};el.onpointerdown=e=>e.stopPropagation()}else{if(item.kind==='white')el.style.background=item.background||'#fff';if(item.kind==='highlight')el.style.background=item.color||'#ffe35c88';if(item.kind==='rect')el.style.borderColor=item.color||'#1769e0';if(item.kind==='line'){el.style.background=item.color||'#1769e0';el.style.transform=`rotate(${item.angle||0}deg)`}if(item.kind==='image')el.style.backgroundImage=`url(${item.data})`;el.onclick=e=>{e.stopPropagation();selectedId=item.id;render()};el.onpointerdown=e=>startMove(e,item,viewport)}layer.appendChild(el);if((item.kind==='text'||item.kind==='replace')&&item.autoFocus)setTimeout(()=>{item.autoFocus=false;el.focus();document.getSelection()?.selectAllChildren(el)},0)})}
function editOriginal(meta){const existing=pageSpec().items.find(i=>i.kind==='replace'&&i.originalId===meta.originalId);if(existing){existing.autoFocus=true;selectedId=existing.id;render();return}snapshot();const item={id:crypto.randomUUID(),kind:'replace',originalId:meta.originalId,originalText:meta.text,text:meta.text,x:meta.x,y:meta.y,w:Math.max(meta.w,2),h:Math.max(meta.h,1),fontSize:meta.fontSize,fontFamily:meta.fontFamily,fontKey:meta.fontKey,color:meta.color,background:meta.background,autoFocus:true};pageSpec().items.push(item);selectedId=item.id;render()}
function addItem(kind,x=16,y=16,extra={}){snapshot();const item={id:crypto.randomUUID(),kind,x,y,w:kind==='text'?34:kind==='line'?25:24,h:kind==='text'?5:kind==='line'?.35:8,text:'Scrivi qui',fontSize:16,fontKey:'helvetica',color:'#1769e0',background:'#ffffff',angle:0,...extra};pageSpec().items.push(item);selectedId=item.id;if(kind==='text')item.autoFocus=true;setTool('select');render()}
function startMove(e,item,viewport){if(tool!=='select')return;e.preventDefault();e.stopPropagation();snapshot();selectedId=item.id;const sx=e.clientX,sy=e.clientY,ox=item.x,oy=item.y;const move=ev=>{item.x=clamp(ox+pct(ev.clientX-sx,viewport.width),0,99);item.y=clamp(oy+pct(ev.clientY-sy,viewport.height),0,99);const el=layer.querySelector(`[data-id="${item.id}"]`);if(el){el.style.left=px(item.x,viewport.width)+'px';el.style.top=px(item.y,viewport.height)+'px'}};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);render()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
sheet.onpointerdown=e=>{if((e.target!==canvas&&e.target!==sheet)||!pdf)return;const r=sheet.getBoundingClientRect(),x=pct(e.clientX-r.left,r.width),y=pct(e.clientY-r.top,r.height);if(tool==='select'){selectedId='';render();return}if(tool==='text'){addItem('text',x,y);return}if(['white','highlight','rect','line'].includes(tool)){snapshot();const kind=tool,id=crypto.randomUUID(),item={id,kind,x,y,w:.1,h:.1,color:kind==='highlight'?'#ffe35c88':'#1769e0',background:'#fff',angle:0};pageSpec().items.push(item);const sx=e.clientX,sy=e.clientY;const move=ev=>{const dx=pct(ev.clientX-sx,r.width),dy=pct(ev.clientY-sy,r.height);item.x=dx<0?x+dx:x;item.y=dy<0?y+dy:y;item.w=Math.max(.2,Math.abs(dx));item.h=kind==='line'?.35:Math.max(.2,Math.abs(dy));if(kind==='line')item.angle=Math.atan2(ev.clientY-sy,ev.clientX-sx)*180/Math.PI;renderItems({width:r.width,height:r.height})};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);selectedId=id;setTool('select');render()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}};
function removeSelected(){if(!selectedId)return;snapshot();pageSpec().items=pageSpec().items.filter(i=>i.id!==selectedId);selectedId='';render()}
function sanitize(s){return String(s).replace(/[^\u0000-\u00ff\u20ac\u2018-\u201d\u2022\u2013\u2014]/g,'?')}
function rgbFromHex(value){const v=(value||'#000000').replace('#','');const n=parseInt(v.length===3?v.split('').map(c=>c+c).join(''):v,16);return PDFLIB.rgb(((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255)}
function dataBytes(url){return Uint8Array.from(atob(url.split(',')[1]||''),c=>c.charCodeAt(0))}
function wrap(text,font,size,maxWidth){const lines=[];for(const paragraph of String(text).split('\n')){if(!paragraph){lines.push('');continue}let line='';for(const word of paragraph.split(/\s+/)){const c=line?line+' '+word:word;let width;try{width=font.widthOfTextAtSize(c,size)}catch{width=c.length*size*.5}if(width>maxWidth&&line){lines.push(line);line=word}else line=c}lines.push(line)}return lines}
async function downloadPdf(){if(!sourceBytes)return;try{toast('Creo il PDF modificato…');const input=await PDFLIB.PDFDocument.load(sourceBytes.slice(0),{ignoreEncryption:true}),out=await PDFLIB.PDFDocument.create(),fonts={};for(const spec of pages){const [p]=await out.copyPages(input,[spec.source]);out.addPage(p);const total=(p.getRotation().angle+spec.rot)%360;p.setRotation(PDFLIB.degrees(total));const W=p.getWidth(),H=p.getHeight();for(const item of spec.items){const X=W*item.x/100,Y=H-H*(item.y+item.h)/100,w=W*item.w/100,h=H*item.h/100;if(item.kind==='white'||item.kind==='replace')p.drawRectangle({x:X,y:Y,width:w,height:h,color:rgbFromHex(item.background||'#ffffff')});if(item.kind==='highlight')p.drawRectangle({x:X,y:Y,width:w,height:h,color:PDFLIB.rgb(1,.82,.05),opacity:.42});if(item.kind==='rect')p.drawRectangle({x:X,y:Y,width:w,height:h,borderColor:rgbFromHex(item.color),borderWidth:2});if(item.kind==='line')p.drawLine({start:{x:X,y:Y+h/2},end:{x:X+w,y:Y+h/2},thickness:2,color:rgbFromHex(item.color)});if(item.kind==='text'||item.kind==='replace'){const key=item.fontKey||'helvetica';if(!fonts[key])fonts[key]=await out.embedFont(key==='times'?PDFLIB.StandardFonts.TimesRoman:key==='courier'?PDFLIB.StandardFonts.Courier:PDFLIB.StandardFonts.Helvetica);const font=fonts[key],size=Math.max(5,item.fontSize||14),lines=wrap(sanitize(item.text),font,size,Math.max(8,w-3));lines.forEach((line,n)=>p.drawText(line,{x:X+1.5,y:Y+h-size*(n+1)*1.08+.5,size,font,color:rgbFromHex(item.color||'#111111'),maxWidth:Math.max(8,w-3)}))}if(item.kind==='image'){const b=dataBytes(item.data),im=item.data.startsWith('data:image/png')?await out.embedPng(b):await out.embedJpg(b);p.drawImage(im,{x:X,y:Y,width:w,height:h})}}}const bytes=await out.save(),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=baseName+'-modificato.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('PDF scaricato con le modifiche.')}catch(e){console.error(e);toast('Errore nell’esportazione. Prova con un PDF non protetto.')}}
$('#tools').onclick=e=>{const b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool)};$('#open').onclick=()=>$('#pdfinput').click();$('#pdfinput').onchange=e=>{loadFile(e.target.files[0]);e.target.value=''};$('#download').onclick=downloadPdf;$('#undo').onclick=()=>restore(history,future);$('#redo').onclick=()=>restore(future,history);$('#remove').onclick=removeSelected;$('#prev').onclick=()=>{if(current>0){current--;selectedId='';render()}};$('#next').onclick=()=>{if(current<pages.length-1){current++;selectedId='';render()}};$('#minus').onclick=()=>{zoom=Math.max(.4,+(zoom-.15).toFixed(2));render()};$('#plus').onclick=()=>{zoom=Math.min(2.5,+(zoom+.15).toFixed(2));render()};$('#rotate').onclick=()=>{snapshot();pageSpec().rot=(pageSpec().rot+90)%360;selectedId='';render()};$('#duplicate').onclick=()=>{snapshot();const copy=deep(pageSpec());copy.items.forEach(i=>i.id=crypto.randomUUID());pages.splice(current+1,0,copy);current++;render()};$('#deletepage').onclick=()=>{if(pages.length<=1)return;snapshot();pages.splice(current,1);current=Math.min(current,pages.length-1);render()};$('#imginput').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>addItem('image',18,18,{w:32,h:22,data:reader.result});reader.readAsDataURL(file);e.target.value=''};$('#drop').ondragover=e=>{e.preventDefault();$('#welcome').classList.add('drag')};$('#drop').ondragleave=()=>$('#welcome').classList.remove('drag');$('#drop').ondrop=e=>{e.preventDefault();$('#welcome').classList.remove('drag');const f=[...e.dataTransfer.files].find(f=>f.type==='application/pdf'||/\.pdf$/i.test(f.name));loadFile(f)};window.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?restore(future,history):restore(history,future)}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();restore(future,history)}else if(!typing&&(e.key==='Delete'||e.key==='Backspace'))removeSelected()});updateButtons();
